default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] || "db" %>

development:
  <<: *default
  database: internship_api_development

test:
  <<: *default
  database: internship_api_test

production:
  <<: *default
  database: internship_api_production
